### ISSUE TITLE
Create optimized diagram style

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-umllight#15]
Improve and optimize the diagram style regarding general appearance and regarding the included subset.

- [x] Use Case Diagram (see #3)
- [x] Activity Diagram (see #4)
- [x] Class Diagram (see #5)
- [x] State Machine (see #6)
- [x] Package Diagram (see #7)
- [x] Sequence Diagram (see #8)

**Comment by cdamus** [comment]
This is looking very good, @planger. Can the relationships (associations, dependencies, etc.) be coloured to match the borders of shapes?  It looks discordant to have these lines starkly black in a diagram where otherwise all of the lines are a pleasing blue hue.

**Comment by planger** [comment]
Yes, that would work; I actually had it this way, but decided against -- mainly because things like the diamond of an aggregation etc looked a bit weird. But if the majority is for the blue relationships, we can certainly have them! I can post a pic soon, to collect opinions.

**Comment by planger** [comment]
![image](https://user-images.githubusercontent.com/588090/48066859-026d5680-e1cf-11e8-89b5-cbb55b04e2ab.png)

**Comment by cdamus** [comment]
That looks so much better to my eye.  Diamonds included.  😉 

Now it's just the paper shapes that stick out with their black borders!  I suspect that the same blue would actually work for those, too.

**Comment by cdamus** [comment]
Per discussion in #10, we need to add `ObjectFlow` to the _Acitivty Diagram_.  In the current CSS styling, they show up black, not blue.
