### ISSUE TITLE
Create custom new diagram creation menu

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-umllight#16]
The new diagram creation menu should only allow to create one of the simplified diagram types listed below:

- [ ] Use Case Diagram (see #3)
- [ ] Activity Diagram (see #4)
- [ ] Class Diagram (see #5)
- [ ] State Machine (see #6)
- [ ] Package Diagram (see #7)
- [ ] Sequence Diagram (see #8)

**Comment by cdamus** [comment]
Any thoughts on the **New Table** menu, @planger?

**Comment by planger** [comment]
My initial thought would be to remove tables for now. My impression is that they are not so straightforward to use for newbies. If the stakeholders disagree, we can always get them back, but I wouldn't spend time on them for now other than hiding the menu. Thanks!
